name: Build CD

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --debug

      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.ADAM_TOKEN }}


    name: Build release email
    runs-on: ubuntu-latest
    - uses: dawidd6/action-send-mail@v3
    with:
      # Required mail server address:
      server_address: smtp.gmail.com

      # Required mail server port:
      server_port: 465
      
      # Required mail subject:
      subject: ADAM Mobile APK - New Release

      # Required recipients' addresses:
      to: hamza.6.shakeel@gmail.com
      
      # Required sender full name (address can be skipped):
      from: Muhammad Hamza # <user@example.com>

      # Optional whether this connection use TLS (default is true if server_port is 465)
      secure: true

      # Optional plain body:
      body: Build job of ${{github.repository}} completed successfully!
      
      priority: high