name: Build release email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    name: ADAM App release email
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com

          # Required mail server port:
          server_port: 465

          # Required mail subject:
          subject: ADAM Mobile APK - New Release

          # Required recipients' addresses:
          to: hamza.6.shakeel@gmail.com

          # Required sender full name (address can be skipped):
          from: Muhammad Hamza # <user@example.com>

          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true

          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!

          priority: high
